[project]
name = "Exerceo"
version = "1.0.0"
description = "Remix your exercise and mock papers to brand new mock papers"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chromadb>=1.3.4",
    "dotenv>=0.9.9",
    "openai>=2.6.1",
    "pillow>=12.0.0",
    "pymupdf>=1.26.5",
]
